{{ config(materialized='view') }}
WITH events_4d_lagged AS (
    SELECT
        ID
        ,FLIGHT_ID
        ,TYPE
        ,EVENT_TIME
        ,LONGITUDE
        ,LATITUDE
        ,ALTITUDE
        ,LAG(EVENT_TIME)    OVER (PARTITION BY FLIGHT_ID ORDER BY EVENT_TIME) AS PREV_EVENT_TIME
        ,LAG(LONGITUDE)     OVER (PARTITION BY FLIGHT_ID ORDER BY EVENT_TIME) AS PREV_LONGITUDE
        ,LAG(LATITUDE)         OVER (PARTITION BY FLIGHT_ID ORDER BY EVENT_TIME) AS PREV_LATITUDE
        ,LAG(ALTITUDE)         OVER (PARTITION BY FLIGHT_ID ORDER BY EVENT_TIME) AS PREV_ALTITUDE
    FROM {{ ref( 'fct_events') }}
) SELECT * FROM events_4d_lagged